"""
All strings accessible in Pages & Tests
"""

ANDROID = 'Android'
IOS = 'iOS'
RESULTS_DIRECTORY = 'results'
LOG_FILE_NAME = 'report.log'
BLANK_FIELD = ''
ERROR = 'Problem, '
ERROR_SETTING_CAPS = 'Problem, setting environment specific caps'
ERROR_UTF_ELEMENT = 'Unable to find specific element - '
ERROR_LABEL_NOT_MATCHING = 'Problem, label on specific element is not matching - '
ERROR_SCREEN_NOT_LOADED = 'Problem, screen is not loaded.'
FACEBOOK_OPTION = 'Facebook'
GOOGLE_OPTION = 'Google'
EULA = 'edX End User License Agreement'
TERMS = 'edX Terms of Service and Honor Code'
PRIVACY = 'Privacy Policy'
SELECTED_BY_DEFAULT = '1'
CANCEL_BUTTON = 'Cancel'
TRUE = 'true'
FALSE = 'false'
IS_FIRST_TIME = True
DENY_BUTTON = 'Deny'
ALLOW_BUTTON = 'Allow'
CANCEL_BUTTON_CAPITAL = 'CANCEL'
OK_BUTTON = 'OK'
REMOVE_BUTTON = 'REMOVE'
TOGGLE_OFF_IOS = '0'
TOGGLE_ON_IOS = '1'
DONT_ALLOW_IOS = 'Don’t Allow'
ADD_BUTTON = 'Add'
DONE_BUTTON = 'Done'
REMOVE_BUTTON_IOS = 'Remove'

# NEW LOGISTRATION SCREEN
NEW_LOGIS_EDX_LOGO = 'edX'
NEW_LOGIS_DISCOVER_COURSES = 'Discover Courses'
NEW_LOGIS_REGISTER = 'Register'
NEW_LOGIS_LOGIN = 'Sign In'

# LOGIN SCREEN
EDX_LOGO = 'E D X'
LOGIN_EDX_LOGO = 'edX'
LOGIN_SCREEN_TITLE = 'Sign In'
LOGIN_USER_NAME_WATER_MARK = 'Username or e-mail address'
LOGIN_USER_NAME_WATER_MARK_ANDROID = 'User name or e-mail address'
LOGIN_PASSWORD_WATER_MARK = 'Password'
LOGIN = 'Sign In'
LOGIN_FORGOT_PASSWORD = 'Forgot your password?'
LOGIN_IOS_WITH_EMAIL_DIVIDER = 'Or Sign in with'
# Issue between iOS and Android
LOGIN_ANDROID_WITH_EMAIL_DIVIDER = 'Or sign in with'
LOGIN_FACEBOOK_OPTION = 'Sign in with Facebook'  # 'Facebook'
LOGIN_GOOGLE_OPTION = 'Sign in with Google'  # 'Google'
LOGIN_RESET_PASSWORD_ALERT_TITLE = 'Reset Password'
LOGIN_RESET_PASSWORD_ALERT_MSG = ('Enter the e-mail address for your account, and we\'ll send you '
                                  'instructions to reset your password.')
LOGIN_RESET_PASSWORD_ALERT_MSG_ANDROID = ('Enter the e-mail address for your account, and we’ll'
                                          ' send you instructions to reset your password.')
LOGIN_RESET_PASSWORD_ALERT_OK = 'OK'
LOGIN_RESET_PASSWORD_ALERT_CANCEL = 'Cancel'
LOGIN_RESET_PASSWORD_ALERT_CANCEL_ANDROID = 'CANCEL'
LOGIN_WRONG_CREDENTIALS_ALERT_TITLE = 'Reset Password Error'
LOGIN_WRONG_CREDENTIALS_ALERT_MSG = 'Please make sure your e-mail address is formatted correctly and try again.'
LOGIN_WRONG_CREDENTIALS_ALERT_OK = 'OK'
LOGIN_ANDROID_AGREEMENT = ('By signing in to this app, you agree to the edX End User'
                           ' License Agreement and edX Terms'
                           ' of Service and Honor Code and you acknowledge'
                           ' that edX and each Member process your personal data'
                           ' in accordance with the Privacy Policy.')
LOGIN_IOS_AGREEMENT = ('By signing-in to this app, you agree to the edX End User License Agreement and edX Terms '
                       'of Service and Honor Code and you acknowledge that edX and each Member process your '
                       'personal data in accordance with the  Privacy Policy.')
LOGIN_EULA = 'edX End User License Agreement'
LOGIN_TERMS = 'edX Terms of Service and Honor Code'
LOGIN_PRIVACY = 'Privacy Policy'
LOGIN_PASSWORD_RESET_ALERT_TITLE = 'Password reset e-mail sent'
LOGIN_PASSWORD_RESET_ALERT_MESSAGE = ('We’ve sent a message with password reset instructions to your e-mail address. '
                                      'If you don’t see it in the next few minutes, '
                                      'make sure to check your spam folder.')
LOGIN_EMAIL_ERROR_MESSAGE = 'Please enter your user name or e-mail address and try again.'
LOGIN_PASSWORD_ERROR_MESSAGE = 'Please enter your password and try again.'
LOGIN_PASSWORD_RESET_ALERT_TITLE_IOS = 'Password Reset E-Mail Sent'
LOGIN_PASSWORD_RESET_ALERT_MESSAGE_IOS = ('We\'ve sent a message with password reset instructions '
                                          'to your e-mail address. If you don\'t see it in the next '
                                          'few minutes, make sure to check your spam folder.')

# WHATS NEW SCREEN
WHATS_NEW_DONE = 'Done'
CLOSE_BUTTON_TEXT = 'Close'
WHATS_NEW_Close_button = 'Close'

# MAIN DASHBOARD SCREEN
MAIN_DASHBOARD_PROFILE = 'Profile'  # Typo from dev side
MAIN_DASHBOARD_SCREEN_TITLE = 'Courses'
MAIN_DASHBOARD_NAVIGATION_MENU = 'Navigation Menu'
MAIN_DASHBOARD_COURSES_TAB = 'Courses'
MAIN_DASHBOARD_PROGRAMS_TAB = 'Programs'
MAIN_DASHBOARD_DISCOVERY_TAB = 'Discovery'
MAIN_DASHBOARD_FIND_COURSE = 'Find a Course'
MAIN_DASHBOARD_NAVIGATION_MENU_NAME = 'Profile Menu'
MAIN_DASHBOARD_NAVIGATION_ACCOUNT_OPTION = 'ACCOUNT'

# ACCOUNT SCREEN
ACCOUNT_SCREEN_TITLE = 'Account'
ACCOUNT_LOGOUT = 'Sign out'
ACCOUNT_SETTINGS = 'Settings'
ACCOUNT_SUBMIT_FEEDBACK = 'Submit Feedback'
ACCOUNT_SCREEN_NAVIGATION_ICON = 'Navigate up'
ACCOUNT_SIGNOUT = 'Sign out'

# REGISTER SCREEN
REGISTER_FACEBOOK_BUTTON = 'Continue with Facebook'
REGISTER_GOOGLE_BUTTON = 'Continue with Google'
REGISTER_SCREEN_TITLE = 'Register'
REGISTER_FULL_NAME_LABEL = 'Full Name'
REGISTER_EMAIL_LABEL = 'Email'
REGISTER_USER_NAME_LABEL = 'Public Username'
REGISTER_PASSWORD_LABEL = 'Password'
REGISTER_SCREEN_REGISTER_WITH = 'Register with'
REGISTER_WITH_EMAIL_DIVIDER = 'or register with email'
REGISTER_EMAIL_INSTRUCTIONS = 'This is what you will use to login.'
REGISTER_FULL_NAME_INSTRUCTIONS = 'This name will be used on any certificates that you earn.'
REGISTER_USER_NAME_INSTRUCTIONS = 'The name that will identify you in your courses. It cannot be changed later.'
REGISTER_PASSWORD_INSTRUCTIONS = 'Your password must contain at least 8 characters, including 1 letter & 1 number.'
REGISTER_COUNTRY_DEFAULT_VALUE = 'Country or Region of Residence'
REGISTER_COUNTRY_INSTRUCTIONS = 'The country or region where you live.'
REGISTER_SHOW_OPTIONAL_FIELDS_OPTION = 'Show optional fields'
REGISTER_HIDE_OPTIONAL_FIELDS_OPTION = 'Hide optional fields'
REGISTER_CREATE_MY_ACCOUNT = 'Create my account'
REGISTER_GENDER_DEFAULT_VALUE = 'Gender'
REGISTER_YOB_DEFAULT_VALUE = 'Year of birth'
REGISTER_EDU_DEFAULT_VALUE = 'Highest level of education completed'
REGISTER_INTERESTED_DEFAULT_VALUE = "Tell us why you're interested in edX"
REGISTER_AGREEMENT_ANDROID = ('By creating an account, you agree to the edX '
                              'End User License Agreement and edX Terms of '
                              'Service and Honor Code and you acknowledge '
                              'that edX and each Member process your '
                              'personal data in accordance with the Privacy Policy.')
REGISTER_AGREEMENT = ('By creating an account, you agree to the edX End User License Agreement '
                      'and edX Terms of Service and Honor Code and you acknowledge that edX and '
                      'each Member process your personal data in accordance with the  Privacy Policy.')

# Register Validate Errors
REGISTER_EMAIL_BLANK_ERROR = 'Please enter your Email.'
REGISTER_FULL_NAME_BLANK_ERROR = 'Please enter your Full Name.'
REGISTER_USER_NAME_BLANK_ERROR = 'Please enter your Public Username.'
REGISTER_PASSWORD_BLANK_ERROR = 'Please enter your Password.'
REGISTER_COUNTRY_BLANK_ERROR = 'Select your country or region of residence'

# COURSES DISCOVERY SCREEN
COURSES_DISCOVERY_SCREEN_TITLE = 'Discovery'
COURSES_DISCOVERY_SEARCH_ICON = ''
COURSES_DISCOVERY_SEARCH_EDIT_FIELD = 'Search for courses'
COURSES_DISCOVERY_COURSES_TAB = 'Courses'
COURSES_DISCOVERY_PROGRAMS_TAB = 'Programs'
COURSES_DISCOVERY_DEGREES_TAB = 'Degrees'
COURSES_DISCOVERY_FILTER_COURSES_LABEL = 'FILTER COURSES'
COURSES_DISCOVERY_BROWSE_BY_SUBJECT_LABEL = 'Browse by Subject'
COURSES_DISCOVERY_SUBJECT_NAME = 'Business & Management'
DISCOVER_SUBJECTS_SECTION_TITLE = 'Discovery'
DISCOVERY_VIEW_ALL_SUBJECTS = 'View All Subjects'
DISCOVER_COURSES_SCREEN_TITLE = 'Discover'
DISCOVER_CANCEL = 'Cancel'
DISCOVERY_CLEAR_ALL = 'CLEAR ALL'
COURSES_DISCOVERY_SEARCH_COURSE_IOS = 'Search courses'
COURSES_DISCOVERY_BROWSE_BY_SUBJECT_IOS = 'Browse By Subject'

# MY COURSES LIST
MY_COURSES_LIST_FIND_COURSES_MESSAGE = 'Looking for a new challenge?'
MY_COURSES_LIST_FIND_COURSES_BUTTON_IOS = 'FIND A COURSE'
MY_COURSES_LIST_FIND_COURSES_BUTTON_ANDROID = 'Find a Course'

# NEW LANDING SCREEN
NEW_LANDING_MESSAGE_IOS = 'Courses and programs from the world\'s best universities in your pocket.'
NEW_LANDING_MESSAGE_ANDROID = 'Courses and programs from the world\'s best universities in your pocket.'
NEW_LANDING_SEARCH_COURSES = 'Search our 3000+ courses'
NEW_LANDING_SEARCH_COURSES_IOS = 'Search courses and programs'
NEW_LANDING_CREATE_YOUR_ACCOUNT = 'Register'
NEW_LANDING_LOG_IN = 'Sign In'
NEW_LANDING_SEARCH_TITLE = 'What do you want to learn?'
NEW_LANDING_EXPLORE_BUTTON = 'Explore all courses'

# PROFILE SCREEN
PROFILE_SCREEN_TITLE = 'Profile'
PROFILE_AGE_LIMIT_TEXT = 'You must be over 13 to share a full profile.'
PROFILE_ACCOUNT_SETTINGS_BUTTON = 'Account Settings'
IOS_PROFILE_SCREEN_EDIT_PROFILE_BUTTON_TEXT = 'Edit profile'
IOS_PROFILE_SCREEN_LIMITED_VIEW_MESSAGE = 'You are currently sharing a limited profile'

# COURSE DASHBOARD SCREEN
COURSE_DASHBOARD_SHARE_COURSE = 'Share a course'
COURSE_DASHBOARD_SHARE_COURSE_ANDROID = 'Share your course'
COURSE_DASHBOARD_VIDEOS_TAB = 'Videos'
COURSE_DASHBOARD_DISCUSSION_TAB = 'Discussion'
COURSE_DASHBOARD_DATES_TAB = 'Dates'
COURSE_DASHBOARD_COURSES_TAB = 'Course'
COURSE_DASHBOARD_RESOURCES_TAB = 'Resources'
COURSE_DASHBOARD_HANDOUTS_TITLE = 'Handouts'
COURSE_DASHBOARD_HANDOUTS_ROW = 'Find important course information'
COURSE_DASHBOARD_ANNOUNCEMENT_TITLE = 'Announcements'
COURSE_DASHBOARD_ANNOUNCEMENT_ROW = 'Keep up with the latest news'
COURSE_DASHBOARD_NAVIGATION_ICON = 'Navigate up'
COURSE_DASHBOARD_RESUME_ROW = 'Resume'

# COURSE SUBSECTION SCREEN
# These constants used to verify the view, against the course "Was Alexander Great?"
COURSE_SUBSECTION_CONTENT_ROW_TEXT = 'Study Guide'
COURSE_SUBSECTION_VIDEO_ROW_TEXT = 'Lecture Module 1: Introductions'
COURSE_NAME = 'Was Alexander Great?'
COURSE_NAME_IOS = 'DemoX'
COURSE_SUBSECTION_CONTENT_ROW_TEXT_IOS = 'Welcome to edX'
COURSE_SUBSECTION_VIDEO_ROW_TEXT_IOS = 'Greetings from Anant'

# COURSE HTML COMPONENT SCREEN
COURSE_HTML_COMPONENT_NAVIGATION_ICON = 'Navigate up'
COURSE_HTML_COMPONENT_NEXT_BUTTON = 'Next'
COURSE_HTML_COMPONENT_PREV_BUTTON = 'Previous'

# SETTINGS SCREEN
SETTINGS_SCREEN_NAVIGATION_ICON = 'Navigate up'
SETTINGS_SCREEN_WIFI_SETTINGS_TEXT = 'Wi-Fi only download'
SETTINS_SCREEN_DOWNLOAD_CONTENT_TEXT = 'Only download content when Wi-Fi is turned on'
SETTINS_SCREEN_DOWNLOAD_CONTENT_TEXT_ANDROID = 'Only download content when wi-fi is turned on'
SETTINGS_SCREEN_WIFI_ON_TOGGLE = 'On'
SETTINGS_SCREEN_WIFI_OFF_TOGGLE = 'Off'
SETTINGS_SCREEN_DIALOG_TITLE = 'ALLOW CELLULAR DOWNLOAD'
SETTINGS_SCREEN_DIALOG_MESSAGE = ('Allow your device to download videos over your cellular connection when '
                                  'Wi-Fi is not available. Data charges may apply.')
SETTINGS_SCREEN_DIALOG_DONT_ALLOW_BUTTON = 'DON’T ALLOW'
SETTINGS_SCREEN_DIALOG_ALLOW_BUTTON = 'ALLOW'

# EDIT PROFILE SCREEN
EDIT_PROFILE_SCREEN_TITLE = 'Edit profile'
EDIT_PROFILE_USER_NAME = 'Username:'
EDIT_PROFILE_CHANGE_PHOTO_TEXT = 'Change profile picture'
EDIT_PROFILE_LABEL_TEXT = 'Other learners can see my:'
EDIT_PROFILE_FULL_VIEW_TEXT = 'Full Profile'
EDIT_PROFILE_LIMITED_VIEW_TEXT = 'Limited Profile'
EDIT_PROFILE_INSTRUCTIONS_TEXT = 'A limited profile only shares your username and profile photo.'
EDIT_PROFILE_BIRTH_YEAR_TEXT = 'Birth year:'
EDIT_PROFILE_LOCATION_TEXT = 'Location:'
EDIT_PROFILE_LANGUAGE_TEXT = 'Spoken language:'
EDIT_PROFILE_ABOUT_ME_TEXT = 'About me:'
EDIT_PROFILE_TAKE_PHOTO_TEXT = 'Take photo'
EDIT_PROFILE_CHOOSE_PHOTO_TEXT = 'Choose a photo'
EDIT_PROFILE_REMOVE_PHOTO_TEXT = 'Remove photo'
EDIT_PROFILE_REMOVE_PHOTO_TEXT_IOS = 'Remove'
EDIT_PROFILE_NEW_INFO_TEXT = 'About me: Testing, This is my new info'
EDIT_PROFILE_UPDATE_LANGUAGE_TEXT = 'Spoken language: English'
EDIT_PROFILE_SELECT_LANGUAGE_TEXT = 'Spoken language: Select'
EDIT_PROFILE_CANCEL_PHOTO_POPUP = 'Cancel'
EDIT_PROFILE_LOCATION_TITLE = 'Location'
EDIT_PROFILE_LANGUAGE_TITLE = 'Spoken language'
EDIT_PROFILE_ABOUT_ME_TITLE = 'About me'
EDIT_PROFILE_ALBANIA_LOCATION = 'Albania'
EDIT_PROFILE_ALGERIA_LOCATION = 'Algeria'
EDIT_PROFILE_USER_ENGLISH_LANGUAGE = 'English'
EDIT_PROFILE_USER_ESPERANTO_LANGUAGE = 'Esperanto'
EDIT_PROFILE_CHEVRON_BUTTON = 'chevron'

# VIDEO DASHBOARD SCREEN
VIDEO_DASHBOARD_TV_TITLE = 'Download to Device'
VIDEO_DASHBOARD_DOWNLOAD_BAR = 'Double tap to view current downloads.'
VIDEO_DASHBOARD_TV_SUBTITLE = '8 Videos, 39.23 MB total'
VIDEO_DASHBOARD_DOWNLOAD_TOGGEL_OFF = 'OFF'
VIDEO_DASHBOARD_DOWNLOAD_TOGGEL_ON = 'ON'
VIDEO_DOWNLOAD_PERMISSION_ALLOW_BUTTON = 'Allow'
VIDEO_DOWNLOAD_PERMISSION_DENY_BUTTON = 'Don’t allow'
VIDEO_ICON_ONLINE_STATUS = 'ONLINE'
VIDEO_ICON_DOWNLOADING_STATUS = 'DOWNLOADING'
VIDEO_ICON_DOWNLOADED_STATUS = 'DOWNLOADED'
VIDEO_DASHBOARD_ALL_VIDEOS_DOWNLOADED = 'All Videos Downloaded'
VIDEO_DASHBOARD_ALL_VIDEOS_DOWNLOADED_IOS = 'All Videos Downloaded, 8 Videos, 37.41MB total'
VIDEO_ICON_DOWNLOADED_STATUS_IOS = 'Download'
VIDEO_DASHBOARD_DOWNLOAD_TOGGEL_ON_IOS = '1'
VIDEO_DASHBOARD_DOWNLOAD_TOGGEL_OFF_IOS = '0'
VIDEO_DASHBOARD_DOWNLOAD_ALL_VIDEOS_IOS = 'Download to Device, 8 Videos, 37.41MB total'

# VIDEO SUBSECTION SCREEN
VIDEO_SUBSECTION_TV_SUBTITLE = '2 Videos, 8.82 MB total'

# COURSE DISCUSSIONS DASHBOARD SCREEN
DISCUSSION_SEARCH_POST = 'Search all posts'
DISCUSSION_ALL_POSTS = 'All Posts'
DISCUSSION_MY_FOLLOWING_POSTS = 'Posts I’m Following'
DISCUSSION_GENERAL_POSTS = 'General'
DISCUSSION_SEARCH_RESULTS = 'Search results'
DISCUSSION_DASHBOARD_TITLE = 'Discussion topics'
DISCUSSION_MY_FOLLOWING_POSTS_IOS = "Posts I'm Following"
DISCUSSION_COURSE_FEEDBACK = 'Course Feedback'
DISCUSSION_COURSE_QnA = 'Course Q&A'

# PROFILE OPTIONS SCREEN
PROFILE_OPTIONS_SCREEN_NAVIGATION_ICON = 'Navigate up'
PROFILE_OPTIONS_SCREEN_TITLE = 'Profile'
PROFILE_OPTIONS_VIDEO_SETTINGS_OPTION_LABEL = 'VIDEO SETTINGS'
PROFILE_OPTIONS_VIDEO_SETTINGS_OPTION_LABEL_LOWER = 'Video settings'
PROFILE_OPTIONS_VIDEO_SETTINGS_DESCRIPTION_LABEL = 'Wifi only download'
PROFILE_OPTIONS_VIDEO_QUALITY_DESCRIPTION_LABEL = 'Video download quality'
PROFILE_OPTIONS_PERSONAL_INFORMATION_LABEL_UPPER = 'PERSONAL INFORMATION'
PROFILE_OPTIONS_PERSONAL_INFORMATION_LABEL_LOWER = 'Personal information'
PROFILE_OPTIONS_FEEDBACK_LABEL = 'Submit feedback'
PROFILE_OPTIONS_FEEDBACK_SUBTITLE_LABEL = ('To get more help and learn how to use the edX mobile app, '
                                           'visit our frequently asked questions.')
PROFILE_OPTIONS_SUPPORT_LABEL = 'Get support'
PROFILE_OPTIONS_SUPPORT_SUBTITLE_LABEL = 'Looking to make a feature request or give us some feedback on our app?'
PROFILE_OPTIONS_EMAIL_FEEDBACK_BUTTON = 'Email the support team'
PROFILE_OPTIONS_FAQ_BUTTON = 'View FAQ '
PROFILE_OPTIONS_FAQ_BUTTON_ANDROID = 'View FAQ'
PROFILE_OPTIONS_SIGNOUT_BUTTON = 'Sign out'
PROFILE_OPTIONS_SIGNOUT_VERSION = 'Version 3.2.3 '
PROFILE_OPTIONS_SIGNOUT_VERSION_ANDROID = 'Version 3.2.3 '
PROFILE_OPTIONS_DELETE_ACCOUNT_BUTTON = 'Delete account'
PROFILE_OPTIONS_DELETE_INFO_LABEL = ('Follow the instructions on the next screen to delete your account and '
                                     'all related data.')
DELETE_ACCOUNT_PAGE_TITLE = 'Delete your account'
CELLULAR_DOWNLOAD_POPUP_TITLE_IOS = 'Allow Cellular Download'
CELLULAR_DOWNLOAD_POPUP_MESSAGE_IOS = ('Allow your device to download videos over your cellular connection '
                                       'when Wi-Fi is not available. Data charges may apply.')
CELLULAR_DOWNLOAD_POPUP_ALLOW_BUTTON = 'Allow'
CELLULAR_DOWNLOAD_POPUP_DONT_ALLOW_BUTTON = 'Don\'t allow'
PROFILE_OPTIONS_WIFI_TOGGLE_ON = '1'
PROFILE_OPTIONS_WIFI_TOGGLE_OFF = '0'
PROFILE_OPTIONS_WIFI_TOGGLE_ON_ANDROID = 'ON'
PROFILE_OPTIONS_WIFI_TOGGLE_OFF_ANDROID = 'OFF'
PROFILE_OPTIONS_HELP_CELL_TITLE = 'Help'
PROFILE_OPTIONS_PRIVACY_CELL_LABEL = 'Privacy'
PROFILE_OPTIONS_PRIVACY_POLICY_LABEL = 'Privacy Policy'
PROFILE_OPTIONS_COOKIE_POLICY_LABEL = 'Cookie Policy'
PROFILE_OPTIONS_DO_NOT_SELL_INFO_LABEL = 'Do Not Sell My Personal Information'

# VIDEO DOWNLOAD QUALITY
VIDEO_DOWNLOAD_QUALITY_POPUP_BACK_ICON = 'Profile'
VIDEO_DOWNLOAD_QUALITY_CLOSE_BUTTON = 'Close'
VIDEO_DOWNLOAD_QUALITY_POPUP_TITLE = 'Video download quality'
VIDEO_DOWNLOAD_QUALITY_POPUP_DESCRIPTION = 'This setting is for all video downloads in the edX app.'
VIDEO_DOWNLOAD_AUTO_QUALITY = 'Auto (Recommended)'
VIDEO_DOWNLOAD_360p_QUALITY = '360p (Smallest file size)'
VIDEO_DOWNLOAD_540p_QUALITY = '540p'
VIDEO_DOWNLOAD_720p_QUALITY = '720p (Best quality)'

# COURSE DISCUSSIONS ALL POSTS
COURSE_ALL_POSTS_REFINE_LABEL = 'Refine:'
COURSE_ALL_POSTS_LABEL = 'All Posts'
COURSE_ALL_POSTS_RECENT_ACTIVITY = 'Recent Activity'
COURSE_ALL_POSTS_CREATE_NEW_POST = 'Create a new post'
COURSE_ALL_POSTS_UNREAD = 'Unread'
COURSE_ALL_POSTS_UNANSWERED = 'Unanswered'
COURSE_ALL_POSTS_MOST_ACTIVITY = 'Most Activity'
COURSE_ALL_POSTS_MOST_VOTES = 'Most Votes'
COURSE_ALL_POSTS_LABEL_IOS = 'Filter by All Posts'
COURSE_ALL_POSTS_RECENT_ACTIVITY_IOS = 'Sort by Recent Activity'
COURSE_ALL_POSTS_CANCEL_BUTTON = 'Cancel'
COURSE_ALL_POSTS_UNREAD_IOS = 'Filter by Unread'
COURSE_ALL_POSTS_UNANSWERED_IOS = 'Filter by Unanswered'
COURSE_ALL_POSTS_MOST_ACTIVITY_IOS = 'Sort by Most Activity'
COURSE_ALL_POSTS_MOST_VOTES_IOS = 'Sort by Most Votes'

# COURSE CREATE NEW POSTS
CREATE_POST_DISCUSSION_BUTTON = 'Discussion'
CREATE_POST_QUESTION_BUTTON = 'Question'
CREATE_POSTS_EDIT_TITLE_TEXT = 'Title'
CREATE_POSTS_ADD_DISCUSSION_POST = 'Post discussion'
CREATE_POST_ADD_QUESTION_TEXT = 'Post question'
CREATE_POST_QUESTION_BUTTON_IOS = ' Question'
CREATE_POST_DISCUSSION_BUTTON_IOS = ' Discussion'
CREATE_POSTS_EDIT_TITLE_TEXT_IOS = 'Title *'
CREATE_POST_QUESTION_LABEL_IOS = 'Question *'
CREATE_POST_DISCUSSION_LABEL_IOS = 'Discussion *'
CREATE_POST_TOPIC_SPINNER_TEXT = 'Topic: General'
CREATE_NEW_POST_BUTTON_IOS = ' \xa0 Create a new post'

# DISCUSSION DETAILS SCREEN
DISCUSSION_DETAILS_TEST_RESPONSE = 'Automated test discussion'
DISCUSSION_DETAILS_ADD_RESPONSE_TEXT = 'Add response'
DISCUSSION_DETAILS_ADD_COMMENT_TEXT = 'Add a response'
DISCUSSION_DETAILS_FLYING_MESSAGE_TEXT = 'Your response has been added.'
DISCUSSION_DETAILS_POST_VISIBILITY_TEXT = 'This post is visible to everyone.'
DISCUSSION_DETAILS_RESPONSES_TEXT = '0 responses'
DISCUSSION_DETAILS_VOTE_BUTTON = '0 Votes'
DISCUSSION_DETAILS_UNFOLLOW_BUTTON = ' Unfollow'
DISCUSSION_DETAILS_REPORT_BUTTON = ' Report'
DISCUSSION_DETAILS_RESPONSES_TEXT_IOS = ' 0 responses'
DISCUSSION_DETAILS_VOTE_BUTTON_IOS = ' 0 Votes'
DISCUSSION_DETAILS_ADD_COMMENT_TEXT_IOS = ' \xa0 Add a response'
DISCUSSION_DETAILS_FLYING_MESSAGE_TEXT_IOS = 'Your comment has been added.'

# DATES SCREEN
DATES_HEADER_TITLE = 'Important Dates'
DATES_COURSE_BANNER_TITLE = 'Course Schedule'
DATES_COURSE_BANNER_INFO = ('We built a suggested schedule to help you stay on track. '
                            'But don’t worry – it’s flexible so you can learn at your own pace. '
                            'If you happen to fall behind, you’ll be able to adjust the dates to '
                            'keep yourself on track.')
DATES_CALENDAR_SYNC_TITLE = 'Sync to calendar'
DATES_CALENDAR_SYNC_TOGGLE_ON = 'ON'
DATES_CALENDAR_SYNC_TOGGLE_OFF = 'OFF'
DATES_CALENDAR_SYNC_INFO = 'Automatically sync all deadlines and due dates for this course to your calendar.'
DATES_COURSE_STARTS_TITLE = 'Course starts'
DATES_COURSE_ENDS_TITLE = 'Course ends'
DATES_COURSE_ENDS_DESCRIPTION = 'After the course ends, the course content will be archived and no longer active.'
DATES_CALENDAR_POPUP_TITLE = '“edX” Would Like to Access Your Calendar'
DATES_CALENDAR_POPUP_MESSAGE = ('edX would like to use your calendar list to subscribe to your '
                                'personalized edX calendar for this course.')
CALENDAR_ALERT_PERMISSION_MESSAGE = 'Allow edX to access your calendar?'
ADD_CALENDAR_ALERT_TITLE = 'Add Calendar “edX -'
CALENDAR_EVENTS_ALERT_TITLE = 'has been added to your phone\'s calendar.'
CALENDAR_EVENTS_ALERT_VIEW_BUTTON = 'VIEW EVENTS'
CALENDAR_EVENTS_ALERT_DONE_BUTTON = 'DONE'
REMOVE_CALENDAR_EVENTS_TITLE = 'Remove calendar “edX '
REMOVE_CALENDAR_EVENTS_MESSAGE = 'Would you like to remove the edX calendar “edX -'
DATES_COURSE_BANNER_INFO_IOS = ('We\'ve built a suggested schedule to help you stay on track. '
                                'But don\'t worry—it\'s flexible so you can learn at your own pace. '
                                'If you happen to fall behind on our suggested dates, '
                                'you\'ll be able to adjust them to keep yourself on track.')
CALENDAR_EVENTS_ALERT_VIEW_BUTTON_IOS = 'View Events'
ADD_CALENDAR_ALERT_TITLE_IOS = 'Add calendar "edX - Infinity test course"'
CALENDAR_EVENTS_ALERT_TITLE_IOS = '"edX - Infinity test course" has been added to your calendar.'
REMOVE_CALENDAR_EVENTS_TITLE_IOS = 'Remove calendar "edX - Infinity test course"'
REMOVE_CALENDAR_EVENTS_MESSAGE_IOS = 'Would you like to remove the edX calendar "edX - Infinity test course" ?'
