name: Migrate Travis to Github Actions
on:
  [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip install -r requirements/lint_requirements.txt
        pycodestyle .
        pylint tests
